version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND=http://localhost:8080 # This needs to be the user accesible backend url
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080" # This needs to be accesible to the user too
    environment:
      JWT_SECRET: ======================jzitnik==Spring===========================
      DB_USERNAME: root
      DB_PASSWORD: quizapp
      DATASOURCE_URL: jdbc:mysql://database:3306/QuizAPP
      DISABLE_REGISTER: false
      DISABLE_PROFILE_PICTURE_UPLOAD: false
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - user_profile_pictures:/app/ProfilePictures

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: quizapp
      MYSQL_DATABASE: QuizAPP
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
  user_profile_pictures:
